### ISSUE TITLE
Dynamic type-check compiled incorrectly (C-backend)

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#100]
With the C backend, the dynamic type check for a method with header

```
method check (p:Parser) on (in:String) outputSeq (*out:String) position (n:Number)
```

is compiled incorrectly.  If the `*out` argument has length 2, then we get the error

```
RuntimeError on line 274: Type error: expected Number for argument n (4) of 
check()on()output()position (defined at combinatorTests:109), got String
```

This occurred in _TypesNSemantics/combinatorTests.grace_ before I commented-out the types.
I haven't tried it with the JS backend.

**Comment by apblack** [comment]
It fails in the JS backend too, with a slightly different error message.

**Comment by petercowal** [comment]
As far as I know, Grace no longer supports variable arguments; is this still an issue?

**Comment by apblack** [comment]
No.
