### ISSUE TITLE
Parser gives wrong line numbers in AST

### ISSUE THREAD

**Issue by reid47** [gracelang/minigrace#104]
When run through the parser with `./minigrace --target parse example.grace`, the following code has wrong line numbers listed in the AST.
```
type Person = type {
  age -> Number
  name -> String
}

class person.new(name', age') {
  def name is public = name'
  def age is public = age'
  method getShoeSize {
    return ((name.size * name.size) + age)
  }
}
```

The generated AST is here:

```
6:1 typedec
  1:6 identifierBinding‹Person›
  Value:6:1 typeliteral
      Types:
      Methods:
        3:3 methodtype
          Name: age
          Returns:
            2:10 identifier‹Number›
          Signature:
            2:7 signaturepart: age
              Parameters:
        4:1 methodtype
          Name: name
          Returns:
            3:11 identifier‹String›
          Signature:
            3:8 signaturepart: name
              Parameters:


5:0 blank
6:2 class
  Name: 6:7 identifierBinding‹person›
  Factory method: 6:14 identifierBinding‹new›
  Signature:
    Part: new
      Parameters:
        6:18 identifierBinding‹name'›
        6:25 identifierBinding‹age'›
  Body:
    8:3 defdec
      7:7 identifierBinding‹name›
      Value: 7:24 identifier‹name'›
    9:3 defdec
      8:7 identifierBinding‹age›
      Value: 8:23 identifier‹age'›
    9:1 method
      Name: 9:10 identifierBinding‹getShoeSize›
      Signature:
        Part: getShoeSize
          Parameters:
      Generics:
      Body:
        11:3 return
          10:42 op‹+›
            10:35 op‹*›
              10:19 member‹size›
                10:14 identifier‹name›
              10:31 member‹size›
                10:26 identifier‹name›
            10:39 identifier‹age›
```

To name a few things wrong with the above: the typeDecNode has the line number 6 (same as the following classNode), when it should have the line number 1. In the body of the class, the second defDecNode and the methodNode are both given the same line number (9). The first defDecNode should be at line 7, and the second defDecNode should be at line 8. Note that for the first defDecNode, the two children nodes (`identifierBinding‹name›` and `identifier‹name'›`) have the correct line number, 7.

The line numbers for all tokens generated by the lexer are correct. 

I'm working on going through the parser to figure out where this is coming from.

**Comment by reid47** [comment]
I figured out the problem. In general, when any node is created, its `line` and `linePos` fields are set to `util.linenum` and `util.linepos`. The `next` method moves to the next token in the token list and calls `util.setPosition` to set those two values to those of the new token (`sym`). In some cases, when the end of a method is reached and a node is being created, the last call to `next` incremented `sym`, so `util.linenum` and `util.linepos` were set to those of the following token when the node is created.

To illustrate further: In the example above, consider the line `def name is public = name'`. When `name'` is read, after several method calls, `next` is called from `pushidentifier`. Then we return to the `defdec` method and create a `defDecNode`, which ends up with the line number and line position of the next token (the `def` from line 8). This is why both the line number and line position value are wrong for the `defDecNode`.

I fixed it by saving the value of `sym` at the top of the `defdec` method with `def defTok = sym`. Then at the end, just before the node is created, I inserted `util.setPosition(defTok.line, defTok.linePos)`. In fact, this was already done for some of the other types of nodes (hence why some line numbers/positions came out correct), but not others. So far, I have fixed this problem in the methods `defdec`, `vardec`, `doreturn`, `domethodtype`, `typedec`, and `dotypeLiteral`. There may be more to fix, but this was enough to get my above example working correctly, as shown here:

```
1:1 typedec
  1:6 identifierBinding‹Person›
  Value:1:15 typeliteral
      Types:
      Methods:
        2:3 methodtype
          Name: age
          Returns:
            2:10 identifier‹Number›
          Signature:
            2:7 signaturepart: age
              Parameters:
        3:3 methodtype
          Name: name
          Returns:
            3:11 identifier‹String›
          Signature:
            3:8 signaturepart: name
              Parameters:


5:0 blank
6:2 class
  Name: 6:7 identifierBinding‹person›
  Factory method: 6:14 identifierBinding‹new›
  Signature:
    Part: new
      Parameters:
        6:18 identifierBinding‹name'›
        6:25 identifierBinding‹age'›
  Body:
    7:3 defdec
      7:7 identifierBinding‹name›
      Value: 7:24 identifier‹name'›
    8:3 defdec
      8:7 identifierBinding‹age›
      Value: 8:23 identifier‹age'›
    9:1 method
      Name: 9:10 identifierBinding‹getShoeSize›
      Signature:
        Part: getShoeSize
          Parameters:
      Generics:
      Body:
        10:5 return
          10:42 op‹+›
            10:35 op‹*›
              10:19 member‹size›
                10:14 identifier‹name›
              10:31 member‹size›
                10:26 identifier‹name›
            10:39 identifier‹age›
```

**Comment by reid47** [comment]
Also fixed this same problem for matchCaseNodes, bindNodes, and opNodes. My parser now appears to give proper line numbers and line positions for all nodes.

**Comment by apblack** [comment]
This is good work.  It shows the peril of global variables.  It would be better if the symbol were an argument to the node constructor, so that the line position could be extracted from the symbol directly, rather than through the globals.

I had a group of students working on parser cleanup, but they flames out without doing anything, so it is appropriate now to make these changes.  More will probably show up as time goes on (I've fixed a fair handful of similar issues in the past), but making incremental progress here is good.  

Once you have this tested, please submit a pull request for these changes.
