### ISSUE TITLE
Match failures don't raise a NonExhaustiveMatch Exception

### ISSUE THREAD

**Issue by KimBruce** [gracelang/minigrace#112]
As I read the spec (and it is not completely clear), a match without any matching cases should throw an exception.  The current minigrace implementation allows a failed match to continue without throwing an exception.

def e = true
match (e)
      case {n: Number -> print (n+1)}
      case {s: String -> print ("Got " ++ s)}

print "done"

Executing this prints "done"

**Comment by apblack** [comment]
This seems like a language-design issue to me.  I can see arguments both ways.   I've never found a use for match, of I don't have strong feelings.  Bu the spec should certainly be clear!

**Comment by petercowal** [comment]
Currently, this outputs
```
ProgrammingError on line 2 of match()case()...: non-exhaustive match in match()case()….
  raised at Exception.raise at line 2 of match()case()...
  called from execution environment.
```

**Comment by kjx** [comment]
after correcting indentation & spacing, Kernan says

Uncaught exception:
RuntimeError: match-case fell through
    from «raise(_)», at line 2861 of prelude
    from «fail(_)», at line 251 of prelude
    from «match(_) case(_) case(_)», at line 2 of crap
