### ISSUE TITLE
Unintuitive parse of request with negative argument

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#114]
Consider this program:

```
import "math" as math

print (math.abs 2)
print (math.abs -2)
```

This produces the output:

```
2
Internal error around line 4 of parseError: TypeError: a is undefined
TypeError: a is undefined
```

The problem is that, while the first print statement does what one would expect,  the second print statement is parsed as `print ((math.abs) - (2))`, requesting `math.abs` with zero arguments.   Because
`math.abs` doesn't do any argument checking, this causes the reported internal error when the implementation of abs tries to access its argument.  (If `abs` is defined in Grace, then we get a wrong number of arguments error).

But perhaps the deeper problem is that `-` isn't treated as modifying `2`?

**Comment by KimBruce** [comment]
Perhaps this is one of those places where requiring spaces around binary
operators would solve the ambiguity.  However I also assumed that math.abs
(-2) actually required the parens around the -2.  Otherwise I don't know
how it could be parsed accurately (given the parser knows nothing about the
rarity of the function). However, it certainly should give a better error
message.

**Comment by kjx** [comment]
Kernan does 

> >>> print (math.abs 2)
> 2
> >>> print (math.abs -2)
> 
> source code:1: P1020: Infix operator '-' must have spaces around it

although it doesn’t support a math module right now.

Also, as Kim said:
> also assumed that math.abs (-2) actually required the parens around the -2. 

well yep.

J

**Comment by apblack** [comment]
Math module has gone away, and method arities are now part of method names, so this issue can't happen.  Instead, code like
```
method abs(n:Number) → Number { 
    // returns the absolute valye of n
    n.abs
}

print (abs -2)
```
will produce a static error like this
```
Syntax error: unknown variable or method 'abs'. This may be a spelling mistake or an attempt to access a variable in another scope.
```
The message should include the phrase "did you mean abs(_)?"  This is another issue.
