### ISSUE TITLE
Call to non-existent method elseblock.size on line 229 of ast.grace

### ISSUE THREAD

**Issue by reid47** [gracelang/minigrace#115]
Line 229 of ast.grace is this:
```
if (self.elseblock.size > 0) then {
```
This is within the `toGrace` method for `ifNode`s. When that method is called, we get an error because a `blockNode` like `elseblock` does not have a `size` method. I believe this line should be `if (self.elseblock.body.size > 0) then {` instead. This makes sense with the rest of that `if` statement:

```
if (self.elseblock.size > 0) then {
    s := s ++ "\n" ++ spc ++ "\} else \{"
    for (self.elseblock.body) do { ix ->
        s := s ++ "\n" ++ spc ++ "    " ++ ix.toGrace(depth + 1)
    }
}
```

**Comment by apblack** [comment]
A better fix would be to give `blockNode`s a `size` method, and probably a `do` method too.  Feel free!

**Comment by petercowal** [comment]
It looks like an isntEmpty method was added at some point.
```
if (self.elseblock.isntEmpty) then {
    s := s ++ "\n" ++ spc ++ "\} else \{"
    for (self.elseblock.body) do { ix ->
        s := s ++ "\n" ++ spc ++ "    " ++ ix.toGrace(depth + 1)
    }
}
```
