### ISSUE TITLE
New line characters cut off error messages in web editor

### ISSUE THREAD

**Issue by reid47** [gracelang/minigrace#116]
Note that all of this was discovered using the web editor. Consider the following example:

```
dialect "staticTypes"

var x:String := {
    print "hi"
}
```

This is using the incomplete version of the staticTypes dialect, but I don't think that affects this problem. Clearly, `x` should be a String but is given a Block, so we raise a TypeError. However, what prints is this:

```
Def TypeError: the expression `{
    in "typechecktest" (line 47, column 2)
```

The error message gets cut off after the first {. The code that raises this exception is here:

```
...
DefError.raiseWith("the expression `{value.toGrace(0)}` of type " ++
    "'{vType}' does not satisfy the type of {defd.kind} " ++
    "annotation '{defType}'", value)
...
```

The problem seems to be that the strings returned by the `toGrace` method for `astNode`s often include new line characters (`\n`). The error message gets cut off right at the first new line character.

**Comment by apblack** [comment]
Does it work correctly at the command-line?

**Comment by reid47** [comment]
Yes, it works at the command-line. This is the output there:
```
Def TypeError: the expression `{
    print("hi")
}` of type 'Block' does not satisfy the type of vardec annotation 'String'.
  2: 
  3: v ar x:String := {
------^
```

**Comment by petercowal** [comment]
When given the following code
```
var x:String := {
    print "hi"
}
```
the current web editor outputs the following:
```
TypeError on line 2 of hello: initial value of var 'x' is not of type String
  raised at execution environment.
   1: 
   2: var x:String := {
   3:     print "hi"
Stack frames:
  hello module
    x = block<hello:2>
```
This looks like a reasonable error message to me; it looks like this issue's been fixed.

**Comment by apblack** [comment]
I believe that this is still open.  The problem is with the grace web editor, which does indeed truncate th eerror message after the first newline.
