### ISSUE TITLE
Generics failure

### ISSUE THREAD

**Issue by KimBruce** [gracelang/minigrace#117]
The following code (in GenericTestFail.grace in the bugs svn repository):
```
type Thing<T> = {
    elt -> T
    elt:= (_:T) -> Done
}

class thing.new<T>(init:T) -> Thing<T> {
    var elt: T is public := init
}

def t: Thing<Number> = thing.new<Number>(5)
```
fails with the following error message:

```
Internal compiler error at line 165 of ast. ProgrammingError: fakeSymbolTable.thatDefines(Number).
    in "genericTest"
```

While Number is clearly defined in other programs, it seems to have constructed the AST before resolving the type name.

**Comment by apblack** [comment]
I can't seem to find the file.

**Comment by KimBruce** [comment]
Sorry, I forgot to commit it.  It is there now.

**Comment by apblack** [comment]
This is now fixed.  The visit method for calls was not visiting the type parameters.  I've also improved the error messages that are generated when type checks fail.

These changes are in commit 94b57c71e
