### ISSUE TITLE
Points don't understand /

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#118]
This code
```
def ovalSize = 50@40
framedOval.at(point - (ovalSize/2)) size(ovalSize.x, ovalSize.y) on (canvas)
```
produces the error
```
NoSuchMethod at line 10 of ex1: no method '/' in object (50@40).
  called from object./ (defined nowhere in object at StandardPrelude:307) at ex1:10
```

**Comment by apblack** [comment]
I added / and * between Points and Numbers in commit a0af85834c14805237d4cbe7aff5e896b09406ea.  They should also be defined between Numbers and Points; tho swill require doing a double dispatch in Number.  This would not slow down the fast path,which is to check that both args of arithmetic operators are native Numbers.   I'll leave this issue open until this is done.

**Comment by KimBruce** [comment]
I can understand (4 @ 6) / 2, but I'm not sure what 10 / (5 @ 2) would be (
2 @ 5?).  Perhaps just leave it in a method on Points and not on Numbers
with a point argument?

**Comment by apblack** [comment]
Good "point", Kim.  I was thinking of `10 * (5@2)`, but not  `10 / (5@2)`.
