### ISSUE TITLE
Exponents are not parsed correctly

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#122]
`print(3e2)`  yields the error message
```
Syntax error: 'e' is not a valid digit in base 10. Valid digits are '0' to '9'.
    in "exponent" (line 1, column 8)
```
It looks as if the parser is not recognizing the `e` at all.  According to the spec (§4.2) this should work.

**Comment by KimBruce** [comment]
As far as I know, that has never been recognized. I noticed it when writing
the book. I

**Comment by apblack** [comment]
I know.  But it's in the spec, and we should support it.  So this is a way of putting it on my to-do list.

**Comment by petercowal** [comment]
The rewritten lexer adds support for exponents.  `print 1.2e-1`, for instance, will output `0.12`.
