### ISSUE TITLE
method and class with same name: crashes compiler

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#13]
I originally reported this by email on 28 May 2014.  The program that produces the crash is in  .../Grace/Bugs/sameNameTwice.grace 

    //  This program crashes the compiler: "no method iter in memberNode".
    //  If you change one of the identifiers
    //  "map" to "mop", then it compiles OK.  The bug seems to be specific to the
    //  class syntax; if you change the class map delcaration to def map = ...
    //  then it compiles OK.

    class anEnumerableTrait {
        method map(block1) {
           ...
        }
    }

    class map.with(*a) {
        inherits anEnumerableTrait
    }

    // Here is the error message given on compilation.

    //Available methods are:
    //  outer  kind  value  value:=  in  accept  map()before()after  map  pretty
    //  toGrace
    //Error around line 141: RuntimeError: no method iter in memberNode.
    //  called from memberNode.iter (defined nowhere in object at ast:1146) at genc:141
    //  called from NativePrelude.for()do (defined at unknown:0 in StandardPrelude module) at genc:141
    //  called from Module<genc>.escapeident (defined at genc:139 in genc module) at genc:99
    //  called from Block[genc:90]._apply (defined at genc:82) at mgcollections:97
    //  called from Block[genc:90].apply (defined at unknown:0) at mgcollections:97
    //  called from NativePrelude.for()do (defined at unknown:0 in StandardPrelude module) at genc:90
    //  called from Module<genc>.definebindings (defined at genc:88 in genc module) at genc:2131
    //  called from Module<genc>.compile (defined at genc:1998 in genc module) at minigrace:124
    //  called from Block[minigrace:123]._apply (defined at minigrace:122) at minigrace:134
    //  called from Block[minigrace:123].applyIndirectly (defined at unknown:0) at minigrace:134
    //  called from Block[minigrace:123].match (defined at unknown:0) at minigrace:134
    //    140:     var ns := ""
    //    141:     for (s) do { c ->
    //    142:         def o = c.ord

**Comment by ryan52** [comment]
This example seems to be working for me with current versions using both C and JS.
