### ISSUE TITLE
build error for minigrace-2418

### ISSUE THREAD

**Issue by harryxp** [gracelang/minigrace#131]
I was trying to build minigrace on a clean Vagrant Debian box and got this after `./configure --prefix <path>` and `make`:

> vagrant@jessie-amd64:/vagrant/minigrace-2418$ make install
> install -d /home/vagrant/local/bin /home/vagrant/local/lib/grace/modules /home/vagrant/local/lib/grace /home/vagrant/local/include
> install -m 755 minigrace /home/vagrant/local/bin/minigrace
> install -m 755  /home/vagrant/local/lib/grace/modules
> install: missing destination file operand after ‘/home/vagrant/local/lib/grace/modules’
> Try 'install --help' for more information.
> Makefile:41: recipe for target 'install' failed
> make: **\* [install] Error 1

I believe this is because C_MODULE isn't defined in Makefile.

**Comment by harryxp** [comment]
Similar problems exist for these two lines in the Makefile:

> install -m 644 $(GRACE_MODULES) $(GRACE_MODULES:%.grace=%.gct) $(MODULE_PATH)
> install -m 644 $(GRACE_DIALECTS) $(GRACE_DIALECTS:%.grace=%.gct) $(GRACE_DIALECTS:%.grace=%.gso) $(GRACE_DIALECTS:%.grace=%.gcn) $(MODULE_PATH)

**Comment by harryxp** [comment]
As a side note, I failed to install a working copy with --prefix, which is my preferred way if I can't install it with a system package manager.  I did all I could including using LD_LIBRARY_PATH but minigrace still complains about not being able to find gracelib.o.  I had to use the default path and I'm glad I was on Vagrant!

**Comment by apblack** [comment]
I have no experience with Debian or it's build systems.  It's quite possible that make configure doesn't work properly for Debian. If you can fix it, that would be great (provided that you don't break the Linux and Darwin builds!)

That first `install` command comes from 

```
install -d $(PREFIX)/bin $(MODULE_PATH) $(OBJECT_PATH) $(INCLUDE_PATH)
```
so it would seem that `$(OBJECT_PATH)` and `$(INCLUDE_PATH)` are not defined.  On my system, these are defined by make configure; my `Makefile.conf` reads:

```
PREFIX ?= /usr
LDFLAGS =  -lm
UNICODE_LDFLAGS = -Wl,-undefined -Wl,dynamic_lookup
UNICODE_MODULE = unicode.gso
STATIC_MODULES = 
OTHER_MODULES = mirrors.gso curl.gso
STUBS = StandardPrelude.grace collectionsPrelude.grace dom.grace imports.grace io.grace mirrors.grace sys.grace timer.grace unicode.grace 
LIBRARY_MODULES = createJsGraphicsWrapper.grace gUnit.grace graphix.grace math.grace minitest.grace unixFilePath.grace 
INCLUDE_PATH = $(PREFIX)/include
MODULE_PATH = $(PREFIX)/lib/grace/modules
OBJECT_PATH = $(PREFIX)/lib/grace
```

The ?= defines `$(PREFIX)` only if it is not set in the environment; this si the way that the destination of the installation can be controlled.  I don't know anything about a --prefix flag; I see that there is one in ./configure, but I don't know what it does, and it's not used by the Makefile.   The logic in `./configure` around `--prefix` uses `readlink -f`, which fails (illegal option) on Darwin, so I can't even test it.

**Comment by apblack** [comment]
I have retired the C environment, so this will never be fixed.
