### ISSUE TITLE
Set is missing methods

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#139]
The sets defined in the prelude are missing subset and superset methods.  What should we call them?  
`≤` and `≥` ?  `.subsetOf` and `.supersetOf` ?  `⊆` and `⊇` are obvious, but hard to type.

**Comment by kjx** [comment]
containsAll?

or superset / subset?

**Comment by KimBruce** [comment]
SubsetOf & supersetOf seem fine.

**Comment by apblack** [comment]
`isSubset` and `isSuperset` were added in e2575091
