### ISSUE TITLE
Inheriting from a nonexistent object not reported as error

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#14]
While updating gUnit and collections to the new naming regime, I compiled this fragment:

    def bindingTest = object {
        class forMethod(m) {
            inherits gU.aTestCaseNamed(m)
    
            method testStringification {
                assert ((2::4).asString) shouldBe "2::4"
            }

This is erroneous, because the _gU_ module no longer contains a factory method _aTestCaseNamed_; it is now called _testCaseNamed_.   However, no error was reported.  Instead, the **inherits** clause was silently ignored, and then uses of the inherited methods were reported as errors:

	collectionTests.grace[14:13-18]: Syntax error: Unknown method name 'assert()shouldBe'. This may be due to a spelling mistake or trying to access a method within another scope.
	  13:         method testStringification {
	  14:             assert ((2::4).asString) shouldBe "2::4"
	------------------^^^^^^
	  15:         }

**Comment by ryan52** [comment]
I believe this may have been fixed.

The example given does produce the following error in JavaScript:
Syntax error: No method aTestCaseNamed
    in "14" (line 5, column 21)

The example given also produces the following error for C:
foobar.grace[5:21-34]: Syntax error: No method aTestCaseNamed
  4:     class forMethod(m) {
  5:         inherits gU.aTestCaseNamed(m)
-------------------------^^^^^^^^^^^^^^

**Comment by apblack** [comment]
Yes, it was fixed by the re-write of the identifier resolution pass.
