### ISSUE TITLE
Inconsistent Exceptions when requests have insufficient arguments

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#143]
Suppose that one requests a variable arity method with insufficient arguments.
```grace
method min(a, b, *xs) {
    var result := if (a < b) then { a } else { b }
    xs.do { x -> 
        if (x < result) then { result := x }
    }
    result
}

min(4)
```
The C backend says
```
RuntimeError around line 65: insufficient arguments to method min
```
while the JS backend says
```
Internal error around line 19 of minitest: RangeError: Invalid array length
Invalid array length
RangeError: Invalid array length
```
Here the JS backend is crashing, rather than producing a clean exception.  Both backends ought to
raise a more specific error, e.g, `RequestError`, which would be defined as a refinement of `ProgrammingError`.

**Comment by petercowal** [comment]
Since variable length arguments are no longer part of Grace, and thanks to the introduction of better names, this is no longer an issue.
