### ISSUE TITLE
Inheritance error with collections.list

### ISSUE THREAD

**Issue by MJS72** [gracelang/minigrace#146]
``` grace
def a = list.with(1, 2, 3, 4, 5)
def b = newPracticeList(a)
print (b.at(1))
print (b.size)

factory method newPracticeList(lst:List) -> List {
    inherits list.withAll(lst)
}
```

Internal error around line 3 of test: TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined

**Comment by apblack** [comment]
The analogous modern program works:
```
def a = list.withAll[ 1, 2, 3, 4, 5]
def b = newPracticeList(a)
print (b.at(1))
print (b.size)
print (b.at 5)

class newPracticeList(lst:List) -> List {
    inherit list.withAll(lst)
}
```

What does _not_ work is attempting to inherit from `lst >> list` or some other way of manufacturing a list, the result of `>>` may not be fresh.
