### ISSUE TITLE
super not treated properly in blocks

### ISSUE THREAD

**Issue by KimBruce** [gracelang/minigrace#153]
While self is handled properly within a block (redirecting to the enclosing object), super is not.  See the following code:

```
class a {
    method m(n: Number) -> Number {n + 1} 
}

class b {
    inherits a
    method other(k: Number) -> Number {super.m(k)}
    method m(n: Number) -> Number {
        {x: Number -> super.m(n) + x}.apply(1)
    }
}

print (a.m(5))
print (b.other(5))
print (b.m(5))
```
This results in printing 6 and then 6 and then blows up:
```
NoSuchMethod at line 9 of testSuper: no method 'm' in object an object.
  called from object.m (defined nowhere) at testSuper:9
  called from block.apply in testSuper
  called from object.m at line 15 of testSuper
  called from execution environment ...
```

**Comment by kjx** [comment]
> On 12/10/2015, at 7:16am, Kim Bruce <notifications@github.com> wrote:
> 
> This results in printing 6 and then 6 and then blows up:

So in Kernan “0.7” (with MI and named supers) this works fine (see below)

Michael has a Kernan “0.8" candidate running that has aliasing working (see further below)
and it does the right thing

>>>                                                                         
>>>                                                                         
>>> class a {                                                               
...     method m(n: Number) -> Number {n + 1}                               
... }                                                                       
>>>                                                                         
>>> class b {                                                               
...     inherits a                                                          
...     method other(k: Number) -> Number {super.m(k)}                      
...     method m(n: Number) -> Number {                                     
...         {x: Number -> super.m(n) + x}.apply(1)                          
...     }                                                                   
... }                                                                       
>>>                                                                         
>>> print (a.m(5))                                                          
6
>>> print (b.other(5))                                                      
6
>>> print (b.m(5))                                                          
7
>>>   


trait a {
    method m(n: Number) -> Number {n + 1} 
}

trait b {
    inherits a
       alias super_m() = m 
    method other(k: Number) -> Number {super_m(k)}
    method m(n: Number) -> Number {
        {x: Number -> super_m(n) + x}.apply(1)
    }
}

**Comment by apblack** [comment]
I'm not going to fix this, because `super` is no longer in the language.
