### ISSUE TITLE
method valueOf gives a weird error

### ISSUE THREAD

**Issue by kjx** [gracelang/minigrace#157]
in the experimental web editor writing

```
method valueOf(x) { x.apply }
```

gives 

Syntax error: a method name must start with an identifier, operator or []

(had to retail this, couldn't copy from the box) 

the same method with another name is fine

**Comment by apblack** [comment]
Thanks for reporting this.  It's because of a bug in the JavaScript version of stringMap, and the fact that valueOf is a method in object.prototype in JavaScript.

It's fixed in my experimental build.  I will propagate it to the web IDE when I've fixed the _other_ problems in that build
