### ISSUE TITLE
minigrace editor fails

### ISSUE THREAD

**Issue by KimBruce** [gracelang/minigrace#163]
The minigrace editor will not work properly on the objectdraw.grace file from the repository.  It seems to work fine on smaller files, but typing in the objectdraw file generates extra characters or sometimes even eats existing characters.

**Comment by apblack** [comment]
Is the problem having a "file" in the IDE that has the same name as one of the pre-loaded modules?  In other words, can it edit the objectdraw file if you call it something else?

**Comment by KimBruce** [comment]
I only have a problem if the first two lines have the pragmas.  If I erase the pragmas then all is well.

Lately I’ve been using a file with a different name from objectdraw just to avoid confusion.

**Comment by apblack** [comment]
I've verified that this bug sill exists even after our recent changes to grace-web-editor.  So I'm closing this and re-opening it in th correct issue tracker.
