### ISSUE TITLE
Objects within a class cannot modify fields

### ISSUE THREAD

**Issue by petercowal** [gracelang/minigrace#186]
```
class foo{
    var i := 1
    def adder = object {
        method add {
            i := i + 1
        }
    }
    method add {
        adder.add
    }
}
def bar = foo
bar.add
```
results in the error
```
NoSuchMethod at line 5 of scopeTest: requested confidential method 'i:=(1)' (defined at scopeTest:2) from outside.
  called from foo.i:=(1) (defined at scopeTest:2 in foo created at scopeTest:1) at scopeTest:5
  called from adder.add (defined at scopeTest:4 in adder created at scopeTest:3) at scopeTest:9
  called from foo.add (defined at scopeTest:8 in foo created at scopeTest:1) at scopeTest:13
    4:         method add {
    5:             i := i + 1
    6:         }
```

This error appears to be exclusive to the betterNames branch.  Note that minigrace *doesn't* complain when *reading* from a class variable, only when trying to write.

**Comment by apblack** [comment]
In _identifierresulution.grace_, there is a pass over the AST that transforms `bindNode`s into requests on methods ending in `:=`.   When these `allNode`s are constructed, they should have the `onSelf` property set (when the receiver is `self` or `outer`).  That should fix this problem.

**Comment by apblack** [comment]
Can you also make the above example into a test?

**Comment by apblack** [comment]
Did you create a test?  Did you try this fix?

**Comment by petercowal** [comment]
I've added a test; the fix was unsuccessful.

**Comment by apblack** [comment]
Oh dear.   The first thing to do is to do _--target ast_ and see if the callNode created for the i:=(_) method  has the `onSelf` attribute.

Note that there are two rewrtings going on here — one to replace the implicit receiver by `outer`, and the other to replace the `bindNode` for `i` with a `callNode`.
