### ISSUE TITLE
Behaviour of multi-line strings is not described in the Specification

### ISSUE THREAD

**Issue by petercowal** [gracelang/minigrace#187]
For instance:
```
def x = 5
print ‹{x}\n›
```
will print
`{x}\n`

I wasn't able to find ‹strings› within the spec, so I'm not sure if this behavior is deliberate or not; I guess that adding strings enclosed in ‹› to the spec is an issue of its own?

**Comment by apblack** [comment]
The use case for multi-line-strings is exactly that they don't support interpolation or string escapes.  Instead, everything between the quotes gies in the string.  The use case is copying a long document (documentation, help message, program text to be used as input, etc) into a program, _without_ having to escape embedded quotes, braces, newlines, etc.

And yes, this should be added to the spec.

**Comment by apblack** [comment]
I added a section to the spec.
