### ISSUE TITLE
Inheritance bug

### ISSUE THREAD

**Issue by KimBruce** [gracelang/minigrace#188]
The following code is extracted from the objectdraw library:

```
class lineFrom (pt: Point) length (len: Number) direction (radians: Number)
          on (canvas':DrawingCanvas) -> Line {
        // Creates a line from pt that has length len, and in direction radians on canvas'
        inherit lineFrom (pt) to (pt + ((len * math.cos (radians)) @
                                        (-len * math.sin (radians)))) on (canvas')
        print (pt + ((len * math.cos (radians)) @
                                        (-len * math.sin (radians))))
}

method lineFrom (pt: Point) length (len: Number) direction (radians: Number)
          on (canvas':DrawingCanvas) -> Line {
        // Creates a line from pt that has length len, and in direction radians on canvas'
        lineFrom (pt) to (pt + ((len * math.cos (radians)) @
                                        (-len * math.sin (radians)))) on (canvas')
}
```
The class definition and the method definition should return exactly the same object when invoked.  While the second one works fine, the first (class definition with inheritance) results in an error:
```
Internal error around line 1213 of od6: TypeError: Cannot read property 'call' of undefined
```
The line cited with the internal error is an invocation of a javascript call to redraw the screen.  Printing out the parameters to the call shows them all defined before the invocation.

Unfortunately I don't see this error with simpler cases of inheritance, so it is hard to know what to attribute this to.  If we had threads I'd worry about it being a race condition, but that doesn't seem relevant here.

Thus the only way I know to reproduce this is to replace the lineFrom()length()direction()on() METHOD in the objectdraw library by the (supposedly identical) class definition and watch it crash on the simplest call of that method.

**Comment by apblack** [comment]
This may have been due to a bug in _dom.js_ that called Grace code from an Javascript event loop without first initializing all of the magic global variables that are needed to support inheritance.
Let me know if the problem has now gone away.

**Comment by KimBruce** [comment]
Thanks. I can't test now, but will when I get back. Excited about the fix!

**Comment by apblack** [comment]
Is this bug still present?  Right now (11th October), the http://www.cs.pdx.edu/~grace/ide is running the old implementation of inheritance (Grace Compiler v3535), which is known to be wrong, but with the patch to _dom.js_ mentioned above.   The http://www.cs.pdx.edu/~black/ide is running a completely new implementation of inheritance (Grace Compiler v3729). I would like to know if this bug is still present on either or both ides.

If it is still present, a self-contained example that manifests the bug would be the first step to tracking it down.

**Comment by KimBruce** [comment]
I'm very happy to say that you have indeed squashed the bug.  Thanks!

(The bug is still visible on my installed implementation -- I likely won't update until after the semester is over, just to be safe!)

**Comment by apblack** [comment]
Was it gone from both the ~grace/ide and ~black/ide ?

**Comment by KimBruce** [comment]
Yes, it fails for both.  You can see it by trying to compile animation.grace from the objectdraw directory.

**Comment by apblack** [comment]
> Yes, it fails for both.

I thought that you said the bug was gone?  Did you mean that inheritance worked in both?

**Comment by KimBruce** [comment]
Sorry, I got two conversations intertwined.  I thought this was the thread for the timer issue.  My fault.  The inheritance bug still exists at ~grace/ide (though if you updated it recently, I might need to flush all the cache's to get the new version), but no bug appears with ~black/ide.

**Comment by apblack** [comment]
OK, so that means that the new inheritance code generation scheme is what kills it.  This is good, because it means that there was some value in doing it!
