### ISSUE TITLE
modules/[rs]tobjectdraw.grace build issues

### ISSUE THREAD

**Issue by ltratt** [gracelang/minigrace#196]
These two files contain the lines:

```import "modules/requireTypes" as rtmethod checker(ast) { rt.checker(ast) }```

and

```import "modules/staticTypes" as stmethod checker(ast) { st.checker(ast) }```

which should both be `[rs]t method <cr> ..." respectively (i.e. `rtmethod` and `stmethod` are not valid keywords).

However, I couldn't immediately work out where these files come from (they seem to be in gitignore files), so I wasn't sure how to fix them.

**Comment by apblack** [comment]
rtobjectdraw and stobjectdraw are generated by a script from objectdraw.grace.  Sounds like the script needs tweaking.   Once we have traits fully implemented, there will be a better way of combining the objectdraw and {static,require}types modules.

**Comment by apblack** [comment]
I think that this is another BSD/Linux problem.  rt- and st- objectdraw are produced by the scripts _make-rt-version_ and _make-st-version_ in the _tools_ directory.  These scripts insert the lines

    import "modules/requireTypes" as rt    
    method checker(ast) { rt.checker(ast) }

(and similarly for st) after the last `import` statement in the file _objectdraw.grace_.  The script works fine on Mac and Linux, but apparently fails to insert a newline between these statements on BSD.

Can you suggest a fix?

**Comment by ltratt** [comment]
I would do something like:

```sh
N=`grep -n ^import "$1" | tail -n 1 | cut -f1 -d:`
head -n $N $1
echo 'import "modules/requireTypes" as rt'
echo 'method checker(ast) { rt.checker(ast) }'
tail -n +$(($N+1)) $1
```

though you'd need to check that also works on your supported platforms.

**Comment by apblack** [comment]
I like that!  Nice and simple — even I can understand it!

These seem to work on Darwin too, so I've committed them to master.
