### ISSUE TITLE
Regular white square brackets aren't supported

### ISSUE THREAD

**Issue by petercowal** [gracelang/minigrace#197]
"Regular" white square brackets (U+301A and U+301B,〚 and 〛) look very similar to mathematical white square brackets (U+27E6 and U+27E7, ⟦ and ⟧), but aren't supported by the language.  It might be a good idea to add another unicode alias.

**Comment by apblack** [comment]
This would be a language change.  If you really think that this is a good idea, then it should be opened as an issue on the _GraceLanguage_ repository.

Unicode already defines two notions of equivalence:  canonical equivalence and compatibility.  We have should probably treat as equivalent anything that unicode treats as canonically equivalent, but _not_ things that Unicode treats as "compatible" — for example, the circled numeral ⓵ is "compatible" with an ordinary 1, and "ffi" is compatible with the ffi ligature.  

Are these two bracket forms canonically equivalent?  I don't think that they are, but it's hard to tell for sure.
