### ISSUE TITLE
Speeding up the garbage collector

### ISSUE THREAD

**Issue by ltratt** [gracelang/minigrace#204]
Looking at minigrace's GC suggested to me that it's likely to be a serious performance bottleneck.

As a quick experiment, I hacked in the Boehm GC (http://www.hboehm.info/gc/) in place of Grace's. I did this by fiddling with the bootstrap VM thingy. I modified `gracelib.c` to add:

`#include <gc.h>`

at the top and then altered the malloc/free/rungc functions to:

```
void *glmalloc(size_t s) {
    return GC_malloc(s);
}
void glfree(void *p) {
}
int rungc() {
    return 1;
}
```

I had to hack the Makefile so that a) minigrace is compiled with `-I/usr/local/include` (since, on my system, that's where Boehm's header files are) b) the main linking phase includes `-lgc -L/usr/local/lib`.

As a quick experiment, here's minigrace compiling a file with the normal Grace GC:

```
time known-good/OpenBSD-amd64/ebebbdf31e78362af099d4a09ba52e11d415ff8e/minigrace  --make --noexec --dir l1 collectionsPrelude.grace

known-good/OpenBSD-amd64/ebebbdf31e78362af099d4a09ba52e11d415ff8e/minigrace    33.02s user 6.43s system 95% cpu 41.136 total
```

and with Boehm GC in its place:

```
time minigrace-3386/minigrace --make --noexec --dir l1 collectionsPrelude.grace

minigrace-3386/minigrace --make --noexec --dir l1 collectionsPrelude.grace  23.63s user 2.18s system 97% cpu 26.522 total
```

So that's 1/3 faster with Boehm. I don't claim that a) you'll see this speed-up all the time b) that it will even work in all cases. But it might be worth someone who's more familiar with the Grace build than I looking into this to see if it's a viable route.

**Comment by apblack** [comment]
Hi Laurie,

Thanks for pointing this out.  I'm frankly surprised that the speedup isn't even more significant!

I have to confess to knowing almost nothing about the internals of the C representation, and to making even the tiniest adjustments with trepidation.  I think this would be a very useful addition to the C-runtime, but I am not the person to make it.
