### ISSUE TITLE
Reloading a file gives bad error message

### ISSUE THREAD

**Issue by KimBruce** [gracelang/minigrace#217]
If you re-load a file that has already been loaded (and perhaps compiled) on the system, you get the following warning (if the file's name is Vehicle.grace):

""Vehicle" is a built-in module. Are you sure you want to overwrite it? Doing so could cause unpredictable behavior!"

A warning is appropriate, but it is not built-in (at least in this case).  Saying something like "you are replacing an existing modules, please be certain this is what you want to do" might be more helpful.

**Comment by Dmitri-2** [comment]
This warning message is actually generated by the web editor when it detects a filename that has already been compiled and loaded onto the webpage. It was originally created to stop people from accidentally creating a file such as "complier.grace" which would break the compilation process. I will add this to my list of things to fix/modify.

**Comment by apblack** [comment]
Moved to [grace-web-editor #40](https://github.com/gracelang/grace-web-editor/issues/40)
