### ISSUE TITLE
Brackets without preceding space — is it still an error?

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#219]
```
def l = list[]
```

and 

```
def l = list[6,7]
```

(without spaces before the left bracket) both give the error

```
argument.grace[1:(14)]: Syntax error: a '[' in an expression must be followed by another expression and a ']'.
```

This is the wrong message.  

```
def l = list[6]
```

gives the message 

```
Syntax error: '[ ... ]' without preceeding space is no longer part of Grace. For a Lineup, add a space.  For an indexing operation, use `at(_)` or `at(_)put(_)`.
```

Is it time to get rid of this error, and accept all three as correct syntax?  Or, should the first two be fixed to generate the same error message as the third (modulo fixing the spelling of "preceding".  Recall that the reason we used Oxford brackets for type parameters is so that it's not necessary to require this space.

**Comment by apblack** [comment]
I'ld like to get a decision on this!

**Comment by KimBruce** [comment]
If there is no ambiguity issue then it would be nice to get rid of the restriction.  It seems to me though that there was some sort of ambiguity that required the space to disambiguate.  E.g. if we see [[b]] is that a list whose only element is the list with element b or is it a type parameter b?

**Comment by apblack** [comment]
> if we see [[b]] is that a list whose only element is the list with element b or is it a type parameter b?

That's determined by whether there is a space between the square brackets.  If there is no space, the [[ and turned into ⟦ and the ]] into ⟧, and you have your answer.

This issue is about whether `foop[5]` is legal, or whether we have to write `foop [5]`.   In my current branch, a program containing the former will always result in:
>Syntax error: '[ ... ]' without preceding space is no longer part of Grace. For a collection, add a space.  For an indexing operation, use `at(_)` or `at(_)put(_)`.

The question is whether we should make it legal, and equivalent to the form with the leading space.

Either way, we need to keep the distinction between `[` and `[[`.

**Comment by kjx** [comment]
The rule for `foop[5]` and `food [5]` should mirror the rules for `foop(5)`and `food  (5)`.

Of course, first we should consider our experience with the lineup design.
I found some old discussion, but I thought there was some newer stuff too

https://github.com/gracelang/language/issues/74
https://github.com/gracelang/language/issues/94

**Comment by apblack** [comment]
Spaces before [ are no longer required, as of commit 6b96980f.
