### ISSUE TITLE
try-catch-finally error

### ISSUE THREAD

**Issue by KimBruce** [gracelang/minigrace#229]
When running whileLiteralExample.grace from the sample/dialects subdirectory, the program crashes with the message
```
Internal compiler error at line 0 of try(_)catch(_)...finally(_). TooMuchRecursion: Does one of your methods request execution of itself without limit?
TooMuchRecursion on line 0 of try(_)catch(_)...finally(_): Does one of your methods request execution of itself without limit?
    in "try(_)catch(_)...finally(_)"
```
Neither the program, nor its dialect (whileLiteral.grace) includes a try()catch() with a finally clause (thought the dialect uses a try()catch() without finally (and does not recursively call itself).  

I suspect the issue is with the compiler itself, but can't tell from the message.  [The whileLiteral dialect does use dialect "dialect", but that doesn't include a finally clause either.]

**Comment by apblack** [comment]
This is quite complicated.

You are right that `Internal compiler error` means that the crash occurred inside the compiler.   But remember that a dialect is _loaded_ inside the compiler, and there is nothing that it can't do!

The infinite recursion is here (lines 10-12 of the whileLiteral dialect):

```
method while(cond)do(block) {
    prelude.while(cond)do(block)
}
```

The second line used to be `_prelude.while ...`, which would have worked.  `prelude` is bound dynamically; perhaps it should be bound statically.   So the effect of the above is to change the meaning of `while(_)do(_)` _inside_ the compiler.

The above would achieve nothing even if it worked, so it should just be deleted. 

There is also a problem with the module-loading mechanism in the _C_ version of the compiler.  The "util" module loaded  by the dialect ought to be the same object as the "util" module loaded by the compiler, but it seems to be getting a new copy.  Consequently, `util.lines`, which holds the source code, is empty and the suggestion machinery does a `BoudnsError`.  This works in the _js_ version of the compiler, though, so I'm not going to try and fix it.

There is now a working dialect in _js/sample/dialects/whileLiteralDialect.grace_ and  _js/sample/dialects/whileLiteralExample.grace_.  I've ignored the _C_ versions.

As far as the _minigrace_ project goes, I'm inclined to remove all of the samples.  They are old and often misleading.  Perhaps we should move them to an _examples_ repository?

**Comment by KimBruce** [comment]
> There is now a working dialect in js/sample/dialects/whileLiteralDialect.grace and js/sample/dialects/whileLiteralExample.grace. I've ignored the C versions.
> As far as the minigrace project goes, I'm inclined to remove all of the samples. They are old and often misleading. Perhaps we should move them to an examples repository?
> 
Thanks for fixing that.  I think it is confusing to have broken code in the repository.  I suggest either adding a suffix “broken”, e.g., “whileLiteral.broken.grace”, or removing it.  The first is only useful if someone will eventually fix it or it is of some historical interest.  In this case, samples seems to be superseded by js/sample, so removing it entirely might be good (or moving the js/sample directory up to replace the original).

I was looking at this because I’m still trying to make some progress on staticTypes.grace.  Right now my big problem is that it doesn’t appear to be executing the check method.  However, I couldn't verify that directly because I couldn't get it to print anything out.  However, I now see that you have managed to get this to happen using io.error.write.  Perhaps you can add that information to your “Writing a Dialect” tutorial.

Kim

**Comment by apblack** [comment]
I think that this issue is fixed.  As part of the fix, I updated _dialect_ so that the various `fail ...` methods generate ranges that are spotted by the compiler, which creates error messages that are recognized by the IDE.  Thus, the IDE will now highlight the correct syntax element.
