### ISSUE TITLE
importing files with .grace in name

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#248]
If one writes (incorrectly)

    import "filename.grace" as nick

the compiler will find and compile  _filename.grace_, as if one had written 

    import "filename" as nick

but there will then be an internal error when the runtime fails to load the compiled version, which it seeks under the name _filename.grace.js_

**Comment by apblack** [comment]
I think that the right behaviour here would be to reject the import statement with the extension.  There should be just one way of doing the import, and that should be by using the basename without an extension.

**Comment by KimBruce** [comment]
Sounds reasonable to me, though I would hope for a specialized error message that would let the user know that the ".grace" suffix was the problem (or maybe even that any suffix is a problem).

**Comment by apblack** [comment]
Of course.  Helpful Messages are Us

**Comment by apblack** [comment]
This is fixed in commit 23d441a
