### ISSUE TITLE
`once class` not recognized

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#274]
The syntax

    once class wombat { ... }

should be legal and have the same meaning as

    once method {
        object { ... }
    }

by analogy with ordinary methods.

This ought to be easy to implement, because `class`es are parsed into `methodNode`s, which already support `once`

**Comment by kjx** [comment]
so, we've built singleton into the language....

**Comment by apblack** [comment]
I think that this is featherweight.  We get Singleton using an object constructor rather than a class.

Should we not have `once class`, and instead require `once method { object ...`?   Seems non-;orthogonal.

**Comment by kjx** [comment]
> On 12/04/2019, at 16:55PM, Andrew Black <notifications@github.com> wrote:
> 
> I think that this is featherweight.

you're right: flyweight. 

> We get Singleton using an object constructor rather than a class.

yeah, I know.
although if the class has no parameters it collapses.

> Should we not have once class, and instead require once method { object ...? Seems non-;orthogonal.

if we have once, we should have the othernce 


although I prefer class/objcet... is once.

**Comment by apblack** [comment]
> although I prefer class/object... is once.

We did talk about that.  Annotations are not supposed to change the semantics — just make things legal or illegal.  I'm not sure if we really observe that rule, though.

**Comment by apblack** [comment]
Fixed in commit be6602a
