### ISSUE TITLE
Infinite loop on default asString method

### ISSUE THREAD

**Issue by aterwl** [gracelang/minigrace#28]
The code below goes in an infinite loop trying to run the default asString method on A. This only occurs when A has (at least?) two B fields.

    type A = {
       one -> B
       two -> B
    }
    
    type B = {
       container -> A
    }
    
    class b.inside(container') -> B {
       def container is public = container'
    }
    
    class a.make -> A {
      def one : B is public = b.inside (self)
      def two : B is public = b.inside (self)
    }
    
    def z : A = a.make
    print(z.one)

**Comment by petercowal** [comment]
The current program output is `a b.b.inside`
