### ISSUE TITLE
RHS of Type Definition isn't Required to be Type Expression

### ISSUE THREAD

**Issue by IsaacOscar** [gracelang/minigrace#289]
According to the [grammar](https://github.com/gracelang/language/blob/master/languageSpec/graceGrammar.txt), the RHS of a type-declaration must be a `TypeExpression` or `InterfaceLiteral`, however the following code does not cause a syntax-error:
```
type X = object{}
```
Despite `object{}` not being a `TypeExpression`.

**Comment by apblack** [comment]
This issue is now resolved.  A test for it was added to t179 in commit b3ee21d3.
