### ISSUE TITLE
Redefining Unknown neither works nor produces an error

### ISSUE THREAD

**Issue by IsaacOscar** [gracelang/minigrace#290]
Redefining `Unknown` does nothing, e.g:
```
type Unknown = interface{foo}
def x: Unknown = object{}
```
The above does not raise a type-error. (Changing `Unknown` to some other name of course does)
I suggest either prohibiting `Unknown` from being redefined, or make redefining work as expected.

**Comment by apblack** [comment]
`Unknown` is reserved in commit 5daa587.
