### ISSUE TITLE
Pattern type omission

### ISSUE THREAD

**Issue by KimBruce** [gracelang/minigrace#309]
A minor issue is that the negation operator is not included in the type Pattern on line 276 of standardGrace.grace.  It is included in trait BasicPattern and hence the other patterns defined in that file, so negation should be added to the type.

**Comment by apblack** [comment]
This is fixed in c3a9f7ea.   There is also now a test (js/tests/t007_types+objects_test.grace) that checks that the basic types and objects correspond.
