### ISSUE TITLE
Type information lost on import

### ISSUE THREAD

**Issue by aterwl** [gracelang/minigrace#32]
Redefining an imported type results in a loss of type information. Create 'A.grace' as below:

    type T = {
      aMethod -> Boolean
    }

And then in another file:

    import "A" as A
    type T = A.T
    print(T.match(1))

This prints a successful match despite 1 not being a valid T. Note this works as expected if you match to A.T directly.

**Comment by petercowal** [comment]
Currently, this outputs `FailedMatch(result = 1, bindings = [])`, so it must've been fixed at some point.
