### ISSUE TITLE
Method in object not called if variable has the same name  

### ISSUE THREAD

**Issue by Malachiain** [gracelang/minigrace#33]
If an object has a method and a var with the same, when the method is called, it will try to access the var instead.

    def triShape = object{
        var bug := "firefly"
        method bug {
          return bug
        }
      }
      print (triShape.bug)

this code will throw :Error around line 7 of editor2: RuntimeError: Requested confidential method 'bug' on Object from outside.
  called from execution environment.

Probably related to #7 and #30

**Comment by ryan52** [comment]
The JS version now gives the following error with this example:
```
Syntax error: 'bug' cannot be redeclared because it is already declared as a vardec on line 2 as well as here at line 3.
    in "test" (line 3, column 12)
```

While the C version gives the following error with the example:
```
foobar.grace[3:12-14]: Syntax error: 'bug' cannot be redeclared because it is already declared as a vardec on line 2 as well as here at line 3.
  2:     var bug := "firefly"
  3:     method bug {
----------------^^^
```

**Comment by apblack** [comment]
That looks like a good error message to me.  I think that we can close this one.
