### ISSUE TITLE
Missing method in scope.grace

### ISSUE THREAD

**Issue by KimBruce** [gracelang/minigrace#331]
Method meet is not defined in class universalScope in module scope.grace.  Error message is
```
Internal compiler error at line 0 of native code. NoSuchMethod: 
no method meet(_) on universalScope the universal scope 
(defined in module scope, line 144)
```
The error is triggered in compiling module Piece in program LineTris by Kim Bruce

**Comment by apblack** [comment]
The missing method is added in commit 78ddd381 (minigrace version 5052).  However, the fix is not tested, because I don't have the code that provokes the error.

**Comment by KimBruce** [comment]
Thanks!  Is it installed on the website?  I can test it there.
