### ISSUE TITLE
Class can not be instantiated before declaration inside an object

### ISSUE THREAD

**Issue by Malachiain** [gracelang/minigrace#34]
If inside an object a class is declared an instance of the class can not be instantiated before the class declaration.
    
    def outside = object{
      inside.new(5)
      class inside.new(five){
        def hay = five
        method say{
          return hay
        }
      }
    }

this will give the syntax error:  Syntax error unknown method or variable name

**Comment by apblack** [comment]
As James says, if one replaces the **class** definition with a  **factory method** definition, all is well.  
Maybe **class**, if we keep it, should desugar to a method, not to a def?

**Comment by petercowal** [comment]
Since classes were modified to desugar to methods at some point, the following
```
def outside = object{
  def in5 is public = insideNew(5)
  class insideNew(five){
    def hay = five
    method say{
      return hay
    }
  }
}

print (outside.in5.say)
```
prints `5` as expected.
