### ISSUE TITLE
What should egal do

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#44]
So long as we have egal in minigrace, we need to decide what it should do.

The last two tests in test 106_egal are

    print(g==e)
    print(hmaker==hmaker)

where

    var e := object {
        def x = "test"
        def z = "hello"
    }
    var g := object {
        def x = "test"
        method z { "hello" }
    }
    method hmaker {
        def word = "hello"
        object {
            def x = "test"
            method z { word }
        }
    }

Both of these print "false" with the C backend.  I changed the JS backend so that they print "true".  What is the rationale for the outcome of the egal test?

My rational was that _egal_ can't, in general, look at the answers from methods, because methods might have arbitrary effects.  They can look only at fields.

So, `g == e`, because `g` has one field, `x`, and `e` has it too, with the same value.  Note, however, that `e != g`, because `e` has two fields (`x` and `z`), and `g` does not have the second one.

Two objects generated by `hmaker` are egal because they have the same fields (just `x`) with the same value.

What is the rational for making the outcomes of these egality tests `false`?

**Comment by petercowal** [comment]
Correct me if I'm wrong, but given that `==` is no longer automatically added to object definitions, this isn't really an issue anymore.
