### ISSUE TITLE
dialect output mixed with code

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#47]
In the (Portland) JS compiler, when a module is used as a dialect, any output (from print methods) is mixed with the generated code.  Naturally enough, this causes syntax errors in the code when it is evaluated.  

Example:

```
// note: no imports!

method myMatch { prelude.SuccessfulMatch.new(1, prelude.list.empty) }

print "myMatch is {myMatch}"

def VariablePattern = prelude.VariablePattern
def AndPattern = prelude.AndPattern
def MatchAndDestructuringPattern = prelude.MatchAndDestructuringPattern
def NoSuchMethod = prelude.NoSuchMethod
def Exception = prelude.Exception

print "end of t155 module"
```

If there are no print statements, then the code seems to work corrrectly.

**Comment by petercowal** [comment]
I tried to replicate this and found that no syntax errors were generated, although modules used as dialects seem to print twice as much as they should.

**Comment by apblack** [comment]
> 
>  modules used as dialects seem to print twice as much as they should.
> 

Top-level prints should execute once when the dialect is loaded at compile time, and again when it is loaded at run time.

**Comment by apblack** [comment]
This issue is being closed because it has been inactive from almost 4 years, and could nto be reproduced when it was investigated.
