### ISSUE TITLE
Inconsistent meaning of "prelude"

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#48]
The pre-defined identifier `prelude` seems to mean the object that surrounds the current module.  In most cases, this is the StandardPrelude.

However, when the current module is written in a dialect, then the surrounding object is not the StandardPrelude.  In this situation, in the C backend, `prelude` means the dialect module.  In the JS backend, `prelude` is treated as if it were defined, but in the generated code it is bound to `var_prelude`, which is an undefined variable, and therefor gives rise to a Javascript error in the eval'd code `ReferenceError: var_prelude is not defined`.

I believe that the C backend is doing the right thing here, and the JS code generator should be altered to agree with it.

**Comment by cameronbwhite** [comment]
In the javascript editor `print(prelude)` will sometimes print the wrong name.

**Comment by apblack** [comment]
I believe that this is fixed in commit 0b1201ca253.  `prelude` is now defined as a local variable in each module, so it can have different values in different modules.
