### ISSUE TITLE
prelude can be redefined

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#49]
The variable name prelude is normally defined to mean the surrounding object.  However, the compiler front-end allows it to be redefined.  For example, it does not object (in a dialect) to one writing

```
import "StandardPrelude" as prelude.
```

However, in this case the generated C code attempts to declare the associated C variable twice:

```
structural.c:25650:9: error: redefinition of 'var_prelude'
 Object *var_prelude = alloc_var();
        ^
 structural.c:25635:11: note: previous definition is here
  Object *var_prelude = alloc_var();
          ^
```

This is of course wrong.  Either the redefinition of `prelude` should be disallowed, or it should work.

**Comment by petercowal** [comment]
Confirmed the bug in C.  Note that the Javascript version happily overrides prelude:
```
import "notPrelude" as prelude
prelude.foo
```
where notPrelude.grace is
```
method foo {
  print "Hello world"
}
```
prints out "Hello world" as expected.
