### ISSUE TITLE
Blocks accepting fewer arguments than they receive

### ISSUE THREAD

**Issue by kjx** [gracelang/minigrace#5]
On 25/06, Kim Bruce wrote:
The following program is (I believe) technically wrong.

```
for(1..3)do{
  print(5)
}
```

Yes, the Minigrace behaviour here is not correct (based on previous email
discussions we've already had about this). The request for 'apply' on the block
in the for() do() method should complain that it has been passed too many
arguments. You should do either this:

```
for (1..3) do { _ ->
  print 5
}
```

Or something like this:

```
method repeat(count) times(block) {
  for (1..count) do { _ ->
    block.apply
  }
}

repeat 3 times {
  print 5
}
```

**Comment by ryan52** [comment]
With the example given, the JavaScript code gives this error:
ProgrammingError at line 1 of 5: block applied to 1 arguments where 0 expected.

This bug seems to only exist in the generated C code currently.

**Comment by petercowal** [comment]
This has been fixed with the introduction of betterNames; the current output of 
```
for (1..3) do {
    print (5)
}
```
is the following
```
No method '_apply(1)'; available methods are: 
...
```

**Comment by KimBruce** [comment]
is there any way of improving that error message for this problem.  This is likely to be a common error for students, yet the error message is very unhelpful.

Kim

**Comment by kjx** [comment]
in particular, that message especially needs to highlight any other method with the _same name but different arity_ to the request.   I've been caught out several times trying to figure out what on earth is wrong now we're overriding on arity.

**Comment by apblack** [comment]
We need to do approximate string matching between the requested method name and the available methods.  The match is already implemented in
errormessages.name (p:String) matches (t:String) within (k:Number)

Fortunately, this is only executed after the program has already failed, so performance of the code that generates the message is not critical.  We can take as much time as we like to build a nice message.

The C backend already lists the available methods; the JS backend should do so too.  Then checking for close matches (edit distance distance 1) is is easy.

**Comment by apblack** [comment]
Commit 90cc973ddcd introduces suggestions in the JS runtime for close matches to methods that don't exist.  Currently, the Hamming distance is set to 1, which will catch most "wrong number of arguments" errors, but also makes some other suggestions.  We can tune these messages if it seems advisable.  

I'm closing this issue.   The situation that it describes is actually covered by a different message — something like 
    block takes 0 arguments but given 1
because blocks are handled specially.

If necessary, we can open a separate issue about the methods suggested after an unhandled NoSuchMethod exception.
