### ISSUE TITLE
Misspelling in error message

### ISSUE THREAD

**Issue by KimBruce** [gracelang/minigrace#60]
Error message if you write something like:   object name ...

Syntax error: An object must have a '{' afer the 'object'.

Replace "afer" by "after"

**Comment by petercowal** [comment]
This seems to have been resolved.
```
object name
standardInput.grace[1:(7)]: Syntax error: an object constructor must have a '{' after the 'object'.
  1: object name
-----------^

Did you mean:
  1: object {} name
```
