### ISSUE TITLE
.gct files are non-deterministic

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#79]
Because the .gct files are written in hash-table order, they are essentially non-deterministic: two .cgt files with the same set of attributes for a field are likely to be different.

This means that there is no easy way, in the compiler or in a makefile, to recompile a module only when the .gct files that it depends on have changed.  Right now, they are recompiled every time.

A simple fix would be to sort the sets and write them to the .gct file in a canonical order.

**Comment by apblack** [comment]
This requires fixing issue #80

**Comment by petercowal** [comment]
Looking at currently generated .gct files, it appears that this issue was fixed.
