### ISSUE TITLE
missing "method" after factory produces stupid error message

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#86]
if one writes 

```
factory methodname { ...
```

the error is

```
Syntax error: Invalid statement. This is often caused by an extra '}', ')', or ']'.
in "inheritance" (line 3, column 1)
```

**Comment by petercowal** [comment]
Since we'll be removing factory methods soon enough, this doesn't seem like a high priority.

**Comment by apblack** [comment]
Factory methods have gone, and so has this error.  We now get a (not very useful) message on seeing the reserved word method:
```
Syntax error: statements must be separated by newlines (or semicolons)
```
