### ISSUE TITLE
Inheritance breaks with definition members

### ISSUE THREAD

**Issue by asasha** [gracelang/minigrace#99]
The use of abstract/super/self does not function when you use definition members in a super object. The workaround appears to be to use methods. 

In our case, we have a super class expression with two objects inheriting from it:

```
factory method expression {
    def containedPredicates = self.predicates
    def states = buildTruthTableStates(self.predicates.size)            
    def results = list.empty() 
    ...
}
```

But when using defs, the expression sub-objects could not find the defs, producing a scope error. Our fix:

```
factory method expression {
  method containedPredicates { self.predicates } 
  method states { buildTruthTableStates(self.predicates.size) } 
  method results { list.empty() }
  ...
}
```

**Comment by apblack** [comment]
I don't get a scope error: the **def**'d names are indeed visible to inheriting objects, as they should be.  

However, the names are not *initialized* until after the sub object is created.  This means that if the sub-object overrides predicates, the overridden version of the method is the one that is executed.  If th overriding version refers to one of th inherited names, you *should* get an initialized variable exception.

**Comment by apblack** [comment]
Without a minimal failing example, I'm going to close this issue.  If it still exists, please re-open it and post complete example code.
